export { default as LandingPage } from "./LandingPage";
export { default as Error } from "./Error";
export { default as DashBoard } from "./DashBoard";
export { default as Register } from "./Register";
export { default as HomeLayout } from "./HomeLayout";
export { default as AllJobs } from "./AllJobs";
export { default as AddJob } from "./AddJob";
export { default as Profile } from "./Profile";
export { default as Login } from "./Login";
